#!/bin/bash

# Helper script to add photos to galleries and update the JavaScript

echo "SOIRAVE Photo Gallery Setup"
echo "============================"
echo ""
echo "This script will help you set up your photo galleries."
echo ""

# Function to scan directory for images
scan_images() {
    local year=$1
    local dir="images/$year"

    if [ ! -d "$dir" ]; then
        return
    fi

    local images=$(find "$dir" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" \) | sort)

    if [ -z "$images" ]; then
        echo "No images found in $dir"
        return
    fi

    echo "Found images in $year:"
    echo "$images" | while read img; do
        echo "  - $img"
    done
    echo ""
}

echo "Scanning for images..."
echo ""

scan_images "2023"
scan_images "2024"
scan_images "2025"

echo ""
echo "To add photos:"
echo "1. Copy your photos to the appropriate year folder:"
echo "   - images/2023/ for BAROQUE EGGPUNK"
echo "   - images/2024/ for ALTEREGGO"
echo "   - images/2025/ for PROEGGBITION"
echo ""
echo "2. Run this script again to see what was added"
echo ""
echo "3. Update js/main.js with the photo paths (see comments in file)"
echo ""
echo "Or use the automatic update option below..."
echo ""

# Ask if user wants to auto-generate the JavaScript
read -p "Would you like to auto-generate the gallery JavaScript? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Generating gallery configuration..."

    # Generate JavaScript arrays
    generate_js_array() {
        local year=$1
        local dir="images/$year"
        local var_name="images$year"

        echo "    const $var_name = ["

        find "$dir" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" \) | sort | while read img; do
            echo "        '$img',"
        done

        echo "    ];"
        echo ""
    }

    # Create updated main.js snippet
    cat > js/gallery-config.js << 'EOF'
// Auto-generated gallery configuration
// This file is generated by add-photos.sh

function loadGalleryImages() {
    const galleries = {
        '2025': document.getElementById('gallery-2025'),
        '2024': document.getElementById('gallery-2024'),
        '2023': document.getElementById('gallery-2023')
    };

EOF

    generate_js_array "2025" >> js/gallery-config.js
    generate_js_array "2024" >> js/gallery-config.js
    generate_js_array "2023" >> js/gallery-config.js

    cat >> js/gallery-config.js << 'EOF'
    // Load 2025 gallery
    if (images2025.length > 0) {
        galleries['2025'].innerHTML = '';
        images2025.forEach(src => {
            const img = document.createElement('img');
            img.src = src;
            img.alt = 'PROEGGBITION 2025';
            img.classList.add('gallery-img');
            galleries['2025'].appendChild(img);
        });
    }

    // Load 2024 gallery
    if (images2024.length > 0) {
        galleries['2024'].innerHTML = '';
        images2024.forEach(src => {
            const img = document.createElement('img');
            img.src = src;
            img.alt = 'ALTEREGGO 2024';
            img.classList.add('gallery-img');
            galleries['2024'].appendChild(img);
        });
    }

    // Load 2023 gallery
    if (images2023.length > 0) {
        galleries['2023'].innerHTML = '';
        images2023.forEach(src => {
            const img = document.createElement('img');
            img.src = src;
            img.alt = 'BAROQUE EGGPUNK 2023';
            img.classList.add('gallery-img');
            galleries['2023'].appendChild(img);
        });
    }
}
EOF

    echo "Gallery configuration generated in js/gallery-config.js"
    echo "Now update js/main.js to use this configuration."
fi
